// Public: the chat widget polls this while open (and briefly in the
// background after a visitor has chatted at least once) to pick up replies
// that were typed from the dashboard rather than generated by the AI.
import { json } from '../../_lib/auth.js';

export async function onRequestGet(context) {
  const { env, params } = context;
  const sessionId = (params.sessionId || '').trim();
  if (!sessionId) return json({ error: 'missing_fields' }, { status: 400 });

  const session = await env.DB.prepare(`SELECT mode FROM chat_sessions WHERE id = ?`).bind(sessionId).first();
  if (!session) return json({ mode: 'ai', messages: [] });

  const { results } = await env.DB.prepare(
    `SELECT id, role, text, created_at FROM chat_messages WHERE session_id = ? ORDER BY created_at ASC LIMIT 200`
  ).bind(sessionId).all();

  return json({
    mode: session.mode,
    messages: results.map(function (m) {
      return { id: m.id, role: m.role, text: m.text, createdAt: m.created_at };
    }),
  });
}
